on: [push]
jobs:
  jmeter_job:
  
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    steps:      
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: PerfAction for JMeter
      uses: QAInsights/PerfAction@v5.6.2
      with:
    # JMeter test plan to execute
        test-plan-path: './Demo.jmx'    
      




        
